name = "xbin"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "PASTEBIN_KV"
id = "c003fc6edc864066bb5a9cf262ce07fe"
preview_id = "c003fc6edc864066bb5a9cf262ce07fe"
